"""Module providing a function to create an Interface for user interaction."""

import gradio as gr
from transformers import pipeline

def text_generation(
        text_prompt:str,
        model:str="gpt2",
        max_length:int=30,
        num_return_sequences:int=1
    ) -> str:
    """ Generate text to complete a sentence

        Parameters
        ----------
            text_prompt : str
                text received as input to the pre-trained model
            model : str, optional
                name of the pre-trained model (default is "gpt2")
            max_length : int
                max generated sentence length (default is 30)
            num_return_sequences : int
                amount of sentences that the model will create (default is 1)

        Returns
        -------
            str
                text generated by the model
    """
    generator = pipeline('text-generation', model=model)
    response = generator(
        text_prompt,
        max_length = max_length,
        num_return_sequences=num_return_sequences
    )
    return response[0]['generated_text']

def text_completion():
    """ Generate interface to user interact with the text completion model

        Returns
        -------
            gradio.interface.Interface
                gradio Interface for user interaction
    """
    textbox = gr.Textbox()
    return gr.Interface(
        fn=text_generation,
        inputs=textbox,
        outputs=textbox
    )
